### ISSUE TITLE
Create wiki page with information on CI server etc.

### ISSUE THREAD

**Issue by deanobob** [natsnudasoft/Tickomon#4]
Can we get a wiki page which details what services are being used for things like continuous integration, package management, etc. and any details on their configuration so we can recreate it if anything goes wrong?

**Comment by deanobob** [comment]
Also, would be useful to have instructions in the wiki for setting up Visual Studio with stylecop, unit testing, etc.

**Comment by natsnudasoft** [comment]
@deanobob What sort of stuff are you imagining would go wrong that would mean we would have to recreate it? 😄
Anyway, I can definitely add some stuff along these lines. What are your opinions though on whether the wiki is the best place for them to go or not, since that's more of a public documentation source; I suppose some sort of "collaborators/contributors" section would make sense in case other github users ever wanted to contribute.

**Comment by deanobob** [comment]
Wherever you think is best, as long as I can access it! :gorilla:

**Comment by natsnudasoft** [comment]
Initial draft of contributing setup [here](https://github.com/natsnudasoft/Tickomon/wiki/Contributing).

Let me know if it all makes sense, and perhaps try to set your environment up and see if you can download and build, and run the project successfully.

You could also test that code analysis works by for example removing the copyright message from ExcludeFromCodeCoverageAttribute.cs and seeing if you get a warning.

You could also check that the DummyTest is discovered and passes (Test -> Windows -> Test -> Test Explorer).
